### ISSUE TITLE
Can you add eclipse user_library support in the next version?

### ISSUE THREAD

**Issue by KonpakuSyl** [microsoft/vscode-java-dependency#174]
## Suggestion

Can you add eclipse user_library support in the next version?

## Use Cases

Every time I add a lot of jars into my project, it will be very troublesome,
So I need an easier way to add jars.

## Examples
Like this

    <classpathentry kind="con" path="org.eclipse.jdt.USER_LIBRARY/7.0sp3"/>

But in the current version it doesn't work.

**Comment by akaroml** [comment]
Thanks for asking. This seems like a nice enhancement for the Java Dependency Viewer.

**Comment by akaroml** [comment]
@testforstephen could you take a look?

**Comment by jdneo** [comment]
Start from `Language Support for Java@0.55.0`, we added a new setting `java.project.referencedLibraries` to config the project classpaths. Please see [this link](https://github.com/redhat-developer/vscode-java/pull/1196#issuecomment-568192224) for usage guide.

Meanwhile, in order to improve the UX, we had this [PR](https://github.com/microsoft/vscode-java-dependency/pull/213) to let the users be able to config this setting from the Dependency Explorer, which will be available in the next version of `Java Dependency Viewer`:
![demo](https://user-images.githubusercontent.com/6193897/72230841-0aa2fc00-35f3-11ea-8d8b-8ec9f04123ad.gif)

Close this issue for now, but please feel free to let us know if you have any thoughts on this.

Thanks.
