### ISSUE TITLE
Support build.gradle.kts

### ISSUE THREAD

**Issue by vrish88** [microsoft/vscode-java-dependency#243]
Hello there,

If you have a project that has a kotlin script gradle file, this extension doesn't pick up the dependencies.

**What I did:**
1. Download https://start.spring.io/#!type=gradle-project&language=kotlin&platformVersion=2.2.5.RELEASE&packaging=jar&jvmVersion=1.8&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=web
1. Open in vscode with this extension.

**What I expected:**
To see all the dependencies declared in the `build.gradle.kts` in the dependency viewer in vscode

**What I saw:**
No dependency viewer in vscode.

**Comment by jdneo** [comment]
Hi @vrish88

Thank you for reporting the issue, while, unfortunately, the current Java Language Server does not support `Kotlin`, so that's the reason why you cannot see anything in the dependency viewer. Actually, the whole Java Language Server is not started up.

More details: https://github.com/redhat-developer/vscode-java/issues/632

I'm closing this issue for now since it's beyond this extension's scope.

Thanks,
