### ISSUE TITLE
Support creation of Maven Projects

### ISSUE THREAD

**Issue by brunoborges** [microsoft/vscode-java-dependency#249]
Currently, the feature "Create Maven Project" is part of the Maven extension.

It is confusing to Java developers, once they have both extensions installed, to have two different "Create Project" actions in the command pallet.

I suggest that this dependency becomes responsible for creating projects (Eclipse, Maven, and Gradle).

Also, see #248

**Comment by jdneo** [comment]
Yes, that's exactly what we want to do in the near future.

One thing I'm considering is that, should we create eclipse project(current behavior) or not? Personally I prefer to use [standalone project](https://code.visualstudio.com/docs/java/java-project#_standalone-java-file-support) instead of eclipse, since creating eclipse project in VS Code looks strange, and the management style of standalone project is more like VS Code way.

**Comment by jdneo** [comment]
PR for hiding Maven command in palette: https://github.com/microsoft/vscode-maven/pull/488
