### ISSUE TITLE
Version 0.11 and above broke JDK8 support

### ISSUE THREAD

**Issue by pschumi** [microsoft/vscode-java-dependency#310]
Java dependencies view does not open when using any version of JDK8. Tested this with multiple projects. The last working version is 1.10.2.

**Comment by jdneo** [comment]
The Java Language Server requires JDK11 to launch now. So the Project Manager extension updates the requirement as well (since it depends on Java Language Server).

I think you need to migrate to JDK11.

**Comment by pschumi** [comment]
Thank you for your quick answer. It would be nice to have this information on "Change log" of the vscode. Unfortunately in my case it is not possible to migrate to JDK11 in near future so I have to stick on older versions in this case.

**Comment by jdneo** [comment]
I think you can migrate to JDK 11 actually. Because it's only used to launch the language server, and you can still use JDK 8 to build your project.

What you need to do is set the setting `java.home` to the location of JDK 11.

And use the setting `java.configuration.runtimes` to specify the location of JDK 8. The language server will pick the most match JDK for your project. (if your project's language level is specified to 8).

See: https://github.com/redhat-developer/vscode-java/issues/1543#issuecomment-663382692

**Comment by Forscyvus** [comment]
Hello I'm having the same issue, and I'm not sure if I've configured the settings correctly. I have 
```{
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "java.home": "C:\\Program Files\\Java\\java-11-openjdk-11.0.8.10-2.windows.redhat.x86_64",
    "java.semanticHighlighting.enabled": true,
    "java.configuration.checkProjectSettingsExclusions": false,
    "java.configuration.runtimes": [
    
        {
            "name": "JavaSE-1.8",
            "path": "C:\\Program Files\\Java\\jdk1.8.0_191"
        }
    ],
    "java.project.referencedLibraries": []
}```

But am still not getting "Java Dependencies" to open... and I need to reference a couple jars to get access to some classes. Help is appreciated!

**Comment by jdneo** [comment]
@Forscyvus could you confirm that the Java Language Server is activated successfully?  (For example, the completion list is working well)

**Comment by Forscyvus** [comment]
It is. Everything seems to be working except that it doesn't know where some of my imports come from. When I was working on this project several weeks ago, I was able to add referenced jars in the Java Dependencies section. (Those jars have updated since, so even if the previous configuration is still there, I think it'd need attention anyway)

**Comment by Forscyvus** [comment]
I can also build my project with maven just fine, the dependency jars are in my local .m2 repo.

**Comment by jdneo** [comment]
@Forscyvus Seems dup with #287 

Please try the command: `Java: Clean the Java language server workspace`

**Comment by Forscyvus** [comment]
I think I have this resolved, though I never got the Java Dependencies thing to display. Something had been renamed in the lib and it was causing a lot of import errors, so it was mostly just me being confused, thanks for your help though!
