### ISSUE TITLE
Apply file decorators to project level

### ISSUE THREAD

**Issue by beckermarc** [microsoft/vscode-java-dependency#481]
In the January blog post on Java in VS Code you announced support for color highlighting / file decoration in the Java Projects Explorer: https://devblogs.microsoft.com/java/java-on-visual-studio-code-update-january-2021/

Is it possible to also provide this color highlighting to the very top of the projects hierarchy, similar to how this is handled in the File Explorer?

For example here I'd also expect the nodes `cds-services` and `cds-feature-jdbc` to be highlighted in yellow:
![image](https://user-images.githubusercontent.com/27853796/113885537-372ad100-97c0-11eb-925c-38129e780a63.png)

I really like the Java Projects Explorer, but this is the main aspect that keeps me from using it regularly. Improving this would make refactorings in big projects much easier were you temporarily might create a lot of compilation issues across various project parts. With the current behaviour it is really hard to spot at a first glance in which project there are still issues or warnings, especially in very big projects.

Thanks a lot!

**Comment by jdneo** [comment]
Thank you for the feedback @beckermarc!

### Some explanation why
Currently we do not highlight the project node on purpose, because with the current implementation, some files are not listed under the project node(for example, pom.xml). If the user only modifies the pom.xml, it will add a decoration at the project node, but when user expands all the children nodes, he will find nothing is changed, that could be annoying.

### Follow-up actions
While this reminds us that we need to consider display these files in the project explorer, this request also appears before: #145, https://github.com/microsoft/vscode-java-dependency/issues/229#issuecomment-582943254. Once this request is implemented, then we can enable the highlighting for the project node.
