### ISSUE TITLE
Project manager extension should have a dependency on Java Extension Pack

### ISSUE THREAD

**Issue by isidorn** [microsoft/vscode-java-dependency#543]
Hi VS Code PM here 👋 

I was just in a user study with @stevencl and a new user to VS Code was setting up Java for VS Code. He fist installed this extension: the Java Package one. It would make good sense if this extension has a dependency on the Java Extension Pack, so if users decide to first install this one that all gets installed together nicely. I do not think this extension makes sense with the basic java one.

fyi @testforstephen 

Let me know what you think, thanks!
Isidor

**Comment by isidorn** [comment]
The user started from this Doc, so he first installed this extension
https://code.visualstudio.com/docs/java/java-project

**Comment by jdneo** [comment]
Hi @isidorn, I'm thinking that whether we need to hard depend on Java Pack, or ask user if he want to have full support of Java then install the Pack.

Also + @akaroml @nickzhums @Eskibear @CsCherrYY

**Comment by Eskibear** [comment]
Java Project Manager extension can work alone to provide limited features, but most features are available [when Java language server is working](https://github.com/microsoft/vscode-java-dependency/blob/e7b4f72eacd0da2364976da6905c14fbf06b7928/package.json#L514-L521) (redhat.java is activated and a Java project is opened).

I think one quick approach is to change the button to "Install Java Extension Pack" in [docs](https://code.visualstudio.com/docs/java/java-project). Because that's what we recommend, and most of the features only work when extension pack is available.

**Comment by isidorn** [comment]
I agree you can also change the docs.
Or whenever a user triggers some of the features that do not work without the java extension pack you would guide the user to install the extension pack.

I personally would make a hard dependency and listen to negative user feedback, but I leave this up to you. 
I understand you wanted to make this extension "lightweight" but we should figure out if users actually use it that way. We should try to get numbers for users that have this extension installed and not the extension pack.

**Comment by Eskibear** [comment]
Action items for now:
- [ ] update docs to install java extension pack. @nickzhums 
- [ ] revisit blocked features and guide to install java extension pack. @jdneo 


> We should try to get numbers for users that have this extension installed and not the extension pack

Agree, to learn how large the impact is. I'll give it a try before we make further decisions.

BTW, I find hard dependency on `redhat.java` was removed by https://github.com/microsoft/vscode-java-dependency/pull/322 . The original intention was to provide useful information while redhat.java is activating (because importing projects can take long time). I'll invite @jdneo to comment if there's further context information.

**Comment by Eskibear** [comment]
> We should try to get numbers for users that have this extension installed and not the extension pack

Statistics shows roughly ~30% machines have project manager installed without extension pack. @jdneo will drive this to optimize the experience for them.

**Comment by jdneo** [comment]
To summarize the actions we've done for this issue:

1. @nickzhums has raised several PRs in VS Code document to guide users install the pack extension.
2. In #547 we will hint user to install the required extension if it's missing. (This can make sure some of the features can still response quickly)
![image](https://user-images.githubusercontent.com/6193897/133578564-b07360b9-23af-4de3-bce2-14c60f741096.png)

I'm closing this issue for now, and let's see if things can be improved with these fixes.

**Comment by isidorn** [comment]
Great, thanks for these improvements 👏
