### ISSUE TITLE
cannot delete/remove "java project"

### ISSUE THREAD

**Issue by bitsofinfo** [microsoft/vscode-java-dependency#707]
Why is there zero ability to remove/delete items under the "java projects" pane?

Why cannot I not import a sub-folder of a workspace (that is a java project) and have it be functioning as a "java project".

Right now I'm stuck with a list of "java projects" that reference items in old workspaces that no longer exist and I can't get rid of these.

**Comment by bitsofinfo** [comment]
maybe related

https://github.com/microsoft/vscode-java-dependency/issues/572

**Comment by goyalyashpal** [comment]
i am facing the same issue. 

### Description & Reproduction:

* Create a java maven project
* Let the "java projects" (& the "maven" too) panel discover it
* Remove the project directory from outside (i did via `rm -r`
* See that "maven" panel no longer shows that project, but "java projects continue to show it

### Screenshots:

![3giSqkpsJB](https://github.com/microsoft/vscode-java-dependency/assets/19423063/9c72076e-290c-4915-aaec-4668656a8979)



### Versions

* `vscjava.vscode-java-dependency`: v0.23.2
* `vscjava.vscode-maven`: v0.42.0
* `redhat.java`: v1.24.0
* VSCodium: Version: 1.84.0 (system setup) Release: 23306
Commit: 695a9146b1347633e608f9f166c81b5b2843b492
* OS: Windows_NT x64 10.0.19045

**Comment by jdneo** [comment]
@goyalyashpal Do you mean that even running `java: Clean Java Language Server Workspace` will not remove them from the explorer?

**Comment by goyalyashpal** [comment]
> even running `java: Clean Java Language Server Workspace` will not remove them from the explorer?

yes

play at 2X speed:


https://github.com/microsoft/vscode-java-dependency/assets/19423063/6374ad55-de32-40cd-a64a-41981155f17e

**Comment by jdneo** [comment]
When trigger the command `java: Clean Java Language Server Workspace`, there should be a notification pops up at the right bottom of the window:

![image](https://github.com/microsoft/vscode-java-dependency/assets/6193897/3ff4461f-9074-4efd-a2d7-8ce94ba216f4)

Then you need to select `Reload and delete`

**Comment by goyalyashpal** [comment]
> there should be a notification pops up at the right bottom of the window:

yes, it worked. thanks.



----
Aside:

is there any difference or exception or exclusion from DND for some notifications?

* as the notifications in the issue of `Request textDocument/documentSymbol failed. Error: name must not be falsy` https://github.com/latex-lsp/texlab/issues/941 
* ... show up despite turning on the "Do Not Disturb Mode" 
* so, i thought the DND was disfunctional, and any notification popup would show up nevertheless 
* that's why my attention didn't go there.




video link: (with inline preview disabled)
https://github.com/microsoft/vscode-java-dependency/assets/19423063/45eee5a1-91a6-40d3-a84c-e42f37fa4589

**Comment by jdneo** [comment]
> is there any difference or exception or exclusion from DND for some notifications?

Ah, I see why you did not see that notification.

Looks like that is a system-wise switch that the extension has no control on it. From extension perspective, maybe we need to consider use another way to show the information instead of notification.

I'm afraid that for now, we don't have a good way to workaround it. Sorry for that.

**Comment by pmingkr** [comment]
Are there any plans to address this issue?
